config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :registrations => "registrations" }

  devise_scope :user do
    post "/accounts/adminview" => "devise/sessions#new"

  end

  root 'home#index'

  get 'home/about'
  get 'home/help'
  get 'home/legal'

  get 'accounts/add_account', to: 'accounts#new'
  post 'accounts/add_account', to: 'accounts#create'

  
  resources :users do
    resources :customers
  end

  resources :customers do
   resources :accounts do
    resources :acct_transactions do
     member do
      get :confirmtf
      get :to_confirm
     end
    end
   end
  end 
    
  resources :accounts do
    resources :acct_transactions 
    resource :wire_transfers
  end
  resources :coin_accounts do
    resource :acct_transactions
  end  
  resources :payees do
      resources :acct_transactions
    end
  resources :customers do
   resources :addresses, :accounts, :coin_accounts, :equities
    member do
      get :manage_accounts
      get :manage_coin_accounts
      get :manage_acct_transactions
      get :customerview
      get :manage_investment_funds
      
    end   
  end
  resources :customers do
    resources :risks, only:[:index,:show,:destroy]
  end
  resources :state do
     resources :zip_codes
  end   
  resources :risks do
    resources :equities 
  end
  resources :account_types, :accounts, :addresses, :administrators, :customers, :transaction_types, :acct_transactions, :users
  resources :coin_accounts, :equity_types, :equities
  

  namespace :admin do
    
    resources :administrators do
     member do
      get :adminview
      get :manage_accounts
      get :manage_customers
      get :manage_acct_transactions
      get :manage_equities
      get :create_customer_account
     end
    end
    resources :accounts do
      resources :acct_transactions
    end
    resources :risks do
      resources :equities 
    end
    resources :users do
     resources :customers
    end
    resources :state do
     resources :zip_codes
    end
    resources :coin_accounts do
      resources :acct_transactions
    end  
    resources :payees do
      resources :acct_transactions
    end
    resources :customers do
      resources :addresses, :accounts, :coin_accounts, :equities
  
      resources :accounts do
        resources :acct_transactions do
          member do
           get :place_onhold
           get :process_transaction
           get :reverse_transaction
          end
        end
      end
        
    end
    
  end
end

app/models/risk.rb
class Risk < ApplicationRecord
    has_many :equities
    has_many :customers, through: :equities
end

app/controllers/admin/risks_controller.rb
class Admin::RisksController < Admin::ApplicationController
  layout "admin"
  before_action :set_risk, only: [:show, :edit, :update, :destroy]

  # GET /risks
  # GET /risks.json
  def index
    @risks = Risk.all
  end

  # GET /risks/1
  # GET /risks/1.json
  def show
  end

  # GET /risks/new
  def new
    @risk = Risk.new
  end

  # GET /risks/1/edit
  def edit
  end

  # POST /risks
  # POST /risks.json
  def create
    @risk = Risk.new(risk_params)

    respond_to do |format|
      if @risk.save
        format.html { redirect_to admin_risk_path(@risk), notice: 'Risk was successfully created.' }
        format.json { render :show, status: :created, location: @risk }
      else
        format.html { render :new }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /risks/1
  # PATCH/PUT /risks/1.json
  def update
    respond_to do |format|
      if @risk.update(risk_params)
        format.html { redirect_to @risk, notice: 'Risk was successfully updated.' }
        format.json { render :show, status: :ok, location: @risk }
      else
        format.html { render :edit }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /risks/1
  # DELETE /risks/1.json
  def destroy
    @risk.destroy
    respond_to do |format|
      format.html { redirect_to risks_url, notice: 'Risk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_risk
      @risk = Risk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def risk_params
      params.require(:risk).permit(:description, :name, :eligibility_group, :situation_type, :amount_covered, :monthly_contribution)
    end
end

app/controllers/risks_controller.rb
class RisksController < ApplicationController
  layout "customer"
  before_action :set_risk, only: [:show, :edit, :update, :destroy]

  # GET /risks
  # GET /risks.json
  def index
    @risks = Risk.all
  end

  # GET /risks/1
  # GET /risks/1.json
  def show
  end

  # GET /risks/new
  def new
    @risk = Risk.new
  end

  # GET /risks/1/edit
  def edit
  end

  # POST /risks
  # POST /risks.json
  def create
    @risk = Risk.new(risk_params)

    respond_to do |format|
      if @risk.save
        format.html { redirect_to admin_risk_path(@risk), notice: 'Risk was successfully created.' }
        format.json { render :show, status: :created, location: @risk }
      else
        format.html { render :new }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /risks/1
  # PATCH/PUT /risks/1.json
  def update
    respond_to do |format|
      if @risk.update(risk_params)
        format.html { redirect_to admin_risk_path(@risk), notice: 'Risk was successfully updated.' }
        format.json { render :show, status: :ok, location: @risk }
      else
        format.html { render :edit }
        format.json { render json: @risk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /risks/1
  # DELETE /risks/1.json
  def destroy
    @risk.destroy
    respond_to do |format|
      format.html { redirect_to risks_url, notice: 'Risk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_risk
      @risk = Risk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def risk_params
      params.require(:risk).permit(:description, :name, :eligibility_group, :situation_type, :amount_covered, :monthly_contribution)
    end
end

app/helpers/risks_helper.rb
module RisksHelper
end

app/views/admin/risks/_form.html.erb
<main>
<div class="panel" style="margin: 10px; padding: 20px;">
  
<%= bootstrap_form_for(risk) do |f| %>
  <% if risk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(risk.errors.count, "error") %> prohibited this risk from being saved:</h2>

      <ul>
      <% risk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%#= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%#= f.label :location %>
    <%= f.text_field :eligibility_group %>
  </div>


  <div class="field">
    <%#= f.label :situation %>
    <%= f.text_field :situation_type %>
  </div>

  <div class="field">
    <%#= f.label :amount_covered %>
    <%= f.text_field :amount_covered %>
  </div>

  <div class="field">
    <%#= f.label :contribution %>
    <%= f.text_field :monthly_contribution %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

  </div>
</main>

app/views/admin/risks/edit.html.erb
<% content_for :admin_content do %>
<h1>Editing Risk</h1>

<%= render 'form', risk: @risk %>

<%= link_to 'Show', @risk %> |
<%= link_to 'Back', risks_path %>
<% end %>

app/views/admin/risks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Risks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Name</th>
      <th>Location</th>
      <th>Interest rate</th>
      <th>Situation</th>
      <th>Amount covered</th>
      <th>Contribution</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @risks.each do |risk| %>
      <tr>
        <td><%= risk.description %></td>
        <td><%= risk.name %></td>
        <td><%= risk.location %></td>
        <td><%= risk.interest_rate %></td>
        <td><%= risk.situation %></td>
        <td><%= risk.amount_covered %></td>
        <td><%= risk.contribution %></td>
        <td><%= link_to 'Show', risk %></td>
        <td><%= link_to 'Edit', edit_risk_path(risk) %></td>
        <td><%= link_to 'Destroy', risk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Risk', new_risk_path %>

app/views/admin/risks/new.html.erb
<% content_for :admin_content do %>
<h1>New Risk</h1>

<%= render 'form', risk: @risk %>

<%= link_to 'Back', risks_path %>
<% end %>

app/views/admin/risks/show.html.erb
<% if admin? %>
<% content_for :admin_content do %>
<main>
<div class="panel" style="margin: 10px; padding: 20px;">
  
<p id="notice"><%= notice %></p>

<div class="panel-heading">Details of your <strong><%= @risk.name %></strong> investment fund </div>
 <div class="panel-body">

<p>
  <strong>Description:</strong>
  <%= @risk.description %>
</p>

<p>
  <strong>Name:</strong>
  <%= @risk.name %>
</p>

<p>
  <strong>Eligible group:</strong>
  <%= @risk.eligibility_group %>
</p>


<p>
  <strong>Situation:</strong>
  <%= @risk.situation_type %>
</p>

<p>
  <strong>Amount covered:</strong>
  <%= number_to_currency(@risk.amount_covered, precision: 2) %>
</p>

<p>
  <strong>Monthly Contribution:</strong>
   <%= number_to_currency(@risk.monthly_contribution, precision: 2) %>
</p>
<% if admin? %>
<%= link_to 'Edit', edit_admin_risk_path(@risk) %> | <%= link_to 'Add Equity', new_admin_risk_equity_path(@risk) %> |
<% end %>
<%= link_to 'Back', :back, :class => "btn btn-primary formButton"  %>

 </div>
 
  </div>
</main>
<% end %>
<% else %>
<% content_for :customer_content do %>
<main>
<div class="panel" style="margin: 10px; padding: 20px;">
  
<p id="notice"><%= notice %></p>

<div class="panel-heading">Details of your <strong><%= @risk.name %></strong> investment fund </div>
 <div class="panel-body">

<p>
  <strong>Description:</strong>
  <%= @risk.description %>
</p>

<p>
  <strong>Name:</strong>
  <%= @risk.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @risk.location %>
</p>

<p>
  <strong>Interest rate type:</strong> 
  <%= @risk.interest_rate %> rate
</p>

<p>
  <strong>Situation:</strong>
  <%= @risk.situation %>
</p>

<p>
  <strong>Amount covered:</strong>
  <%= number_to_currency(@risk.amount_covered, precision: 2) %>
</p>

<p>
  <strong>Contribution:</strong>
   <%= number_to_currency(@risk.contribution, precision: 2) %>
</p>
<% if admin? %>
<%= link_to 'Edit', edit_risk_path(@risk) %> | <%= link_to 'Add Equity', new_risk_equity_path(@risk) %> |
<% end %>
<%= link_to 'Back', :back, :class => "btn btn-primary formButton"  %>

 </div>
 
  </div>
</main>
<% end %>
<% end %>