config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :registrations => "registrations" }

  devise_scope :user do
    post "/accounts/adminview" => "devise/sessions#new"

  end

  root 'home#index'

  get 'home/about'
  get 'home/help'
  get 'home/legal'

  get 'accounts/add_account', to: 'accounts#new'
  post 'accounts/add_account', to: 'accounts#create'

  
  resources :users do
    resources :customers
  end

  resources :customers do
   resources :accounts do
    resources :acct_transactions do
     member do
      get :confirmtf
      get :to_confirm
     end
    end
   end
  end 
    
  resources :accounts do
    resources :acct_transactions 
    resource :wire_transfers
  end
  resources :coin_accounts do
    resource :acct_transactions
  end  
  resources :payees do
      resources :acct_transactions
    end
  resources :customers do
   resources :addresses, :accounts, :coin_accounts, :equities
    member do
      get :manage_accounts
      get :manage_coin_accounts
      get :manage_acct_transactions
      get :customerview
      get :manage_investment_funds
      
    end   
  end
  resources :customers do
    resources :risks, only:[:index,:show,:destroy]
  end
  resources :state do
     resources :zip_codes
  end   
  resources :risks do
    resources :equities 
  end
  resources :account_types, :accounts, :addresses, :administrators, :customers, :transaction_types, :acct_transactions, :users
  resources :coin_accounts, :equity_types, :equities
  

  namespace :admin do
    
    resources :administrators do
     member do
      get :adminview
      get :manage_accounts
      get :manage_customers
      get :manage_acct_transactions
      get :manage_equities
      get :create_customer_account
     end
    end
    resources :accounts do
      resources :acct_transactions
    end
    resources :risks do
      resources :equities 
    end
    resources :users do
     resources :customers
    end
    resources :state do
     resources :zip_codes
    end
    resources :coin_accounts do
      resources :acct_transactions
    end  
    resources :payees do
      resources :acct_transactions
    end
    resources :customers do
      resources :addresses, :accounts, :coin_accounts, :equities
  
      resources :accounts do
        resources :acct_transactions do
          member do
           get :place_onhold
           get :process_transaction
           get :reverse_transaction
          end
        end
      end
        
    end
    
  end
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  belongs_to :user

end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < Admin::ApplicationController
  #call admin layout file
  layout "admin"
  before_filter :authenticate_user!

  before_action :set_administrator, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  def adminview
      # manage_customers
      # redirect_to manage_customers_administrator_path
      # render "_manage_customers"
  end

  # Update adminview content using AJAX and jQuery
  def manage_accounts
    # criteria from the "Search by" select menu
    if params[:search]
        case (params[:search_criteria])
        when '1'
          @criteria = 'id'
        when '2'
          @criteria = 'customer_id'
        when '3'
          
        # when '3' 
        #   Account.includes(:customers).all
        #   @criteria = 'customer.lastname'
        end

        @accounts = Account.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @table_heading = "Account Search Results"
    else
        @accounts = Account.order('id').page(params[:page]).per(15)
        @table_heading = "Listing All Accounts"
    end

    respond_to do |format|
      format.js
      format.html {render 'manage_accounts'}
    end
  end

  def manage_customers
    # criteria from the "Search by" select menu
    if params[:search]
        case (params[:search_criteria])
        when '1'
          @criteria = 'id'
        when '2'
          @criteria = 'lastname'
        end

        @users = User.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @customers = Customer.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @table_heading = "Customer Search Results"
    else
        @users = User.order('username').page(params[:page]).per(15)
        @customers = Customer.order('lastname').page(params[:page]).per(15)
        @table_heading = "Listing All Customers"
    end
    
    respond_to do |format|
      format.js
      format.html {render 'manage_customers'}
    end
  end

  def manage_acct_transactions
    # criteria from the "Search by" select menu
    if params[:search]
        case (params[:search_criteria])
        when '1'
          @criteria = 'id'
        when '2'
          @criteria = 'account_id'
        end

        @acct_transactions = AcctTransaction.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @table_heading = "Transaction Search Results"
    else
        @acct_transactions = AcctTransaction.order('date DESC').page(params[:page]).per(15)
        @table_heading = "Listing All Transactions"
        
    end
    
    respond_to do |format|
      format.js
      format.html {render 'manage_acct_transactions'}
    end
  end

  def manage_equities
    # criteria from the "Search by" select menu
    if params[:search]
        case (params[:search_criteria])
        when '1'
          @criteria = 'id'
        when '2'
          @criteria = 'customer_id'
        when '3'
          
        # when '3' 
        #   Account.includes(:customers).all
        #   @criteria = 'customer.lastname'
        end

        @equities = Equity.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @table_heading = "Equity Search Results"
    else
        @equities = Equity.order('id').page(params[:page]).per(15)
        @risks = Risk.order('id').page(params[:page]).per(15)
        @table_heading = "Listing All Equities"
    end

    respond_to do |format|
      format.js
      format.html {render 'manage_equities'}
    end
  end
  
  def create_customer_account
    #@customer = Customer.find(params[:customer_id])
    @account = Account.new
    @account.id = SecureRandom.random_number(999999999999)
    @account.balance = params[:balance]
    @account.date_opened = Time.now.to_date
    @account.customer_id = params[:customer_id]
    @account.acct_type_id = params[:acct_type_id]
    
      respond_to do |format|
        if @account.save
         format.js
         format.html {render 'manage_accounts'}
       else
         format.js
         format.html {render 'create_customer_account'}
        end
      end
  end    
  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def require_admin
    unless current_user.role == 'admin'
      redirect_to root_path, alert: 'NOT AUTHORIZED!! Redirecting to home page..'
    end
  end

  def check_referer
    case Rails.application.routes.recognize_path(request.referer)[:controller]
        when 'customers'
          manage_customers
        when 'accounts'
          manage_accounts
        when 'acct_transactions'
          manage_acct_transactions
        else
          manage_accounts
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params[:administrator]
    end
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  #call admin layout file
  layout "admin"
  before_filter :authenticate_user!

  before_action :set_administrator, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  def adminview
      # manage_customers
      # redirect_to manage_customers_administrator_path
      # render "_manage_customers"
  end

  # Update adminview content using AJAX and jQuery
  def manage_accounts
    # criteria from the "Search by" select menu
    if params[:search]
        case (params[:search_criteria])
        when '1'
          @criteria = 'id'
        when '2'
          @criteria = 'customer_id'
        when '3'
          
        # when '3' 
        #   Account.includes(:customers).all
        #   @criteria = 'customer.lastname'
        end

        @accounts = Account.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @table_heading = "Account Search Results"
    else
        @accounts = Account.order('id').page(params[:page]).per(15)
        @table_heading = "Listing All Accounts"
    end

    respond_to do |format|
      format.js
      format.html {render 'manage_accounts'}
    end
  end

  def manage_customers
    # criteria from the "Search by" select menu
    if params[:search]
        case (params[:search_criteria])
        when '1'
          @criteria = 'id'
        when '2'
          @criteria = 'lastname'
        end

        @users = User.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @customers = Customer.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @table_heading = "Customer Search Results"
    else
        @users = User.order('username').page(params[:page]).per(15)
        @customers = Customer.order('lastname').page(params[:page]).per(15)
        @table_heading = "Listing All Customers"
    end
    
    respond_to do |format|
      format.js
      format.html {render 'manage_customers'}
    end
  end

  def manage_acct_transactions
    # criteria from the "Search by" select menu
    if params[:search]
        case (params[:search_criteria])
        when '1'
          @criteria = 'id'
        when '2'
          @criteria = 'account_id'
        end

        @acct_transactions = AcctTransaction.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @table_heading = "Transaction Search Results"
    else
        @acct_transactions = AcctTransaction.order('date DESC').page(params[:page]).per(15)
        @table_heading = "Listing All Transactions"
        
    end
    
    respond_to do |format|
      format.js
      format.html {render 'manage_acct_transactions'}
    end
  end

  def manage_equities
    # criteria from the "Search by" select menu
    if params[:search]
        case (params[:search_criteria])
        when '1'
          @criteria = 'id'
        when '2'
          @criteria = 'customer_id'
        when '3'
          
        # when '3' 
        #   Account.includes(:customers).all
        #   @criteria = 'customer.lastname'
        end

        @equities = Equity.where("#{@criteria} LIKE ?", "%#{params[:search].downcase}%").page(params[:page]).per(15)
        @table_heading = "Equity Search Results"
    else
        @equities = Equity.order('id').page(params[:page]).per(15)
        @risks = Risk.order('id').page(params[:page]).per(15)
        @table_heading = "Listing All Equities"
    end

    respond_to do |format|
      format.js
      format.html {render 'manage_equities'}
    end
  end
  
  def create_customer_account
    #@customer = Customer.find(params[:customer_id])
    @account = Account.new
    @account.id = SecureRandom.random_number(999999999999)
    @account.balance = params[:balance]
    @account.date_opened = Time.now.to_date
    @account.customer_id = params[:customer_id]
    @account.acct_type_id = params[:acct_type_id]
    
      respond_to do |format|
        if @account.save
         format.js
         format.html {render 'manage_accounts'}
       else
         format.js
         format.html {render 'create_customer_account'}
        end
      end
  end    
  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def require_admin
    unless current_user.role == 'admin'
      redirect_to root_path, alert: 'NOT AUTHORIZED!! Redirecting to home page..'
    end
  end

  def check_referer
    case Rails.application.routes.recognize_path(request.referer)[:controller]
        when 'customers'
          manage_customers
        when 'accounts'
          manage_accounts
        when 'acct_transactions'
          manage_acct_transactions
        else
          manage_accounts
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params[:administrator]
    end
end

app/views/administrators/manage_accounts.html.erb
<% content_for :admin_content do %>
  <h3 class="table-heading"><%= @table_heading %></h3>
  <%= form_tag manage_accounts_administrator_path, :method => 'get', :id => "search-form" do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Search Accounts', required: true %>
      <%= select_tag("search_criteria", options_for_select([['by account number', '1'],['by customer id', '2'],['by customer last name', '3']], selected: '1', disabled: '3')) %>
      <%= submit_tag "Search", :name => nil %>
  <% end %>
  <br />
    <%= paginate (@accounts) %>
    <table id="indexTable" class="table table-striped">
      <thead>
        <tr>
          <th>Account Number</th>
          <th class="hide-medium">Account Type</th>
          <th>Customer Name</th>
          <th class="hide-medium">Customer ID</th>
          <th class="hide-small">Balance</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% if @accounts.blank? %>
          <tr><td colspan='5' style="text-align: center;"><h4>There are no accounts to display</h4></td></tr>
        <% else %>
          <% @accounts.each do |account| %>
          <tr>
            <td><%= account.id %></td>
            <td class="hide-medium"><%= AcctType.find(account.acct_type_id).name %>
            <td><%= account.customer.lastname %>, <%= account.customer.firstname %></td>
            <td class="hide-medium"><%= account.customer_id %></td>
            <td class="hide-small"><%= number_to_currency(account.balance) %></td>

            <td><%= link_to 'Show', account_path(account), :class=> "btn btn-default" %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= paginate (@accounts) %>
  <br />
  <table id="indexTable" class="table table-striped">
      <thead>
        <tr>
          <th>Account Type Id</th>
          
          <th>Name</th>
          <th class="hide-medium">Status</th>
          
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        
          <% @acct_types.each do |acct_type| %>
          <tr>
            <td><%= acct_type.id %></td>
            <td class="hide-medium"><%= acct_type.name %>
            <td><%= acct_type.status %></td>
            

            <td><%= link_to 'Show', acct_type_path(acct_type), :class=> "btn btn-default" %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <br />
  <%= link_to 'Back', :back, :class => "btn btn-primary formButton"  %>
<% end %>

app/views/administrators/manage_acct_transactions.html.erb
<% content_for :admin_content do %>
  <h3 class="table-heading"><%= @table_heading %></h3>
  <%= form_tag manage_acct_transactions_administrator_path, :method => 'get', :id => "search-form" do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Search Transactions'  %>
      <%= select_tag("search_criteria", options_for_select([['by transaction id', '1'],['by account id', '2']], selected: '1')) %>
      <%= submit_tag "Search", :name => nil, :class => 'btn-search' %>
  <% end %>
  <br />
    <%= paginate (@acct_transactions) %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="hide-small">Date</th>
          <th>Transaction ID</th>
          <th class="hide-medium">Type</th>
          <th class="hide-medium">Account ID</th>
          <th class="hide-large">Description</th>
          <th>Amount</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
          <% @acct_transactions.each do |trans| %>
          <tr>
            <td class="hide-small"><%= trans.date.strftime("%B %d, %Y") %></td>
            <td><%= trans.id %></td>
            <td class="hide-medium"><%= TransactionType.find(trans.transaction_type_id).name %></td>
            <td class="hide-medium"><%= trans.account_id %></td>
            <td class="hide-large"><%= trans.description %></td>
            <td><%= number_to_currency(trans.amount) %></td>
            <td><%= link_to 'Show', acct_transaction_path(trans), :class => "btn btn-default" %></td>
          </tr>
          <% end %>
      </tbody>
    </table>
    <%= paginate (@acct_transactions) %>
    <br />
    <div id='links-block'>
      <%= link_to 'Back', :back, :class => "btn btn-primary formButton"  %>
      <%= link_to 'Return to Dashboard', manage_acct_transactions_administrator_path, :class => "btn btn-info formButton"  %>
    </div>
<% end %>

app/views/administrators/manage_customers.html.erb
<% content_for :admin_content do %>
  <h3 class="table-heading"><%= @table_heading %></h3>
  <%= form_tag manage_customers_administrator_path, :method => 'get', :id => "search-form" do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Search Customers'  %>
      <%= select_tag("search_criteria", options_for_select([['by customer id', '1'],['by customer last name', '2']], selected: '1')) %>
      <%= submit_tag "Search", :name => nil %>
  <% end %>
  <br />
    <%= paginate (@customers) %>
    <table id="indexTable" class="table table-striped">
      <thead>
        <tr>
          <th>Customer ID</th>
          <th class="hide-small">Customer Name</th>
          <th class="hide-small hide-medium hide-large">Phone</th>
          <th class="hide-small hide-medium">Email</th>
          <th colspan="2">Actions</th>
        </tr>
      </thead>
      <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td class="hide-small"><%= customer.lastname %>, <%= customer.firstname %></td>
            <td class="hide-large"><%= customer.phone1 %></td>
            <td class="hide-medium"><%= mail_to customer.user.email %></td>
            <td><%= link_to 'Edit', edit_customer_path(customer), :class => "btn btn-default" %></td>
            <td><%= link_to 'Details', customer_path(customer), :class => "btn btn-default" %></td>
             <td><%= link_to 'Address', edit_customer_address_path(:customer_id => customer.id), :class => "btn btn-default" %></td>            

          </tr>
          <% end %>
      </tbody>
    </table>
    <%= paginate (@customers) %>
  <br />
  <%= link_to 'Back', :back, :class => "btn btn-primary formButton"  %>
   <%= link_to 'Create Customer', new_user_registration_path, :class => "btn btn-primary formButton"  %>
   
   <br />
    <%= paginate (@users) %>
    <table id="indexTable" class="table table-striped">
      <thead>
        <tr>
          <th>User ID</th>
          <th class="hide-small">UserName</th>
          
          <th colspan="2">Actions</th>
        </tr>
      </thead>
      <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td class="hide-small"><%= user.email %>, <%= user.username %></td>
            
            <td><%= link_to 'Edit', edit_user_path(user), :class => "btn btn-default" %></td>
            <td><%= link_to 'Details', user_path(user), :class => "btn btn-default" %></td>
             <td><%= link_to 'Add Customer', new_user_customer_path(user), :class => "btn btn-default" %></td>            

          </tr>
          <% end %>
      </tbody>
    </table>
    <%= paginate (@users) %>
  <br />
<% end %>

app/views/administrators/manage_equities.html.erb
<% content_for :admin_content do %>
  <h3 class="table-heading"><%= @table_heading %></h3>
  <%= form_tag manage_equities_administrator_path, :method => 'get', :id => "search-form" do %>
      <%= text_field_tag :search, params[:search], placeholder: 'Search Equities'  %>
      <%= select_tag("search_criteria", options_for_select([['by equity id', '1'],['by customer last name', '2']], selected: '1')) %>
      <%= submit_tag "Search", :name => nil %>
  <% end %>
  <br />
    <%= paginate (@equities) %>
    <table id="indexTable" class="table table-striped">
      <thead>
        <tr>
          <th>Equity ID</th>
          <th class="hide-small">Certificate No</th>
          <th class="hide-small hide-medium hide-large">Issue Date</th>
          <th class="hide-small hide-medium">Equity Type</th>
          <th class="hide-small hide-medium">Currency</th>
          <th colspan="2">Actions</th>
        </tr>
      </thead>
      <tbody>
          <% @equities.each do |equity| %>
          <tr>
            <td><%= equity.id %></td>
            <td class="hide-small"><%= equity.certificat_number %></td>
            <td class="hide-large"><%= equity.issue_date %></td>
            <td class="hide-medium"><%= equity.equity_type.name %></td>
            <td class="hide-medium"><%= equity.bill_currency %></td>
            <td><%= link_to 'Edit', edit_equity_path(equity), :class => "btn btn-default" %></td>
            <td><%= link_to 'Details', equity_path(equity), :class => "btn btn-default" %></td>
             <td><%= link_to 'Risk', edit_risk_path(equity.risk_id), :class => "btn btn-default" %></td>            

          </tr>
          <% end %>
      </tbody>
    </table>
    <%= paginate (@equities) %>
  <br />
  <%= link_to 'Back', :back, :class => "btn btn-primary formButton"  %>
   <%= link_to 'Create Risk', new_risk_path, :class => "btn btn-primary formButton"  %>
   
   <br />
    <%= paginate (@risks) %>
    <table id="indexTable" class="table table-striped">
      <thead>
        <tr>
          <th>Risk ID</th>
          <th class="hide-small">Risk Name</th>
          
          <th colspan="2">Actions</th>
        </tr>
      </thead>
      <tbody>
          <% @risks.each do |risk| %>
          <tr>
            <td><%= risk.id %></td>
            <td class="hide-small"><%= risk.name %>, <%= risk.interest_rate %></td>
            
            <td><%= link_to 'Edit', edit_risk_path(risk), :class => "btn btn-default" %></td>
            <td><%= link_to 'Details', risk_path(risk), :class => "btn btn-default" %></td>
             <td><%= link_to 'Add Equity', new_risk_equity_path(risk), :class => "btn btn-default" %></td>            

          </tr>
          <% end %>
      </tbody>
    </table>
    <%= paginate (@risks) %>
  <br />
  
<% end %>