config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, :controllers => { :registrations => "registrations" }

  devise_scope :user do
    post "/accounts/adminview" => "devise/sessions#new"

  end

  root 'home#index'

  get 'home/about'
  get 'home/help'
  get 'home/legal'

  get 'accounts/add_account', to: 'accounts#new'
  post 'accounts/add_account', to: 'accounts#create'

  
  resources :users do
    resources :customers
  end

  resources :customers do
   resources :accounts do
    resources :acct_transactions do
     member do
      get :confirmtf
      get :to_confirm
     end
    end
   end
  end 
    
  resources :accounts do
    resources :acct_transactions 
    resource :wire_transfers
  end
  resources :coin_accounts do
    resource :acct_transactions
  end  
  resources :payees do
      resources :acct_transactions
    end
  resources :customers do
   resources :addresses, :accounts, :coin_accounts, :equities
    member do
      get :manage_accounts
      get :manage_coin_accounts
      get :manage_acct_transactions
      get :customerview
      get :manage_investment_funds
      
    end   
  end
  resources :customers do
    resources :risks, only:[:index,:show,:destroy]
  end
  resources :state do
     resources :zip_codes
  end   
  resources :risks do
    resources :equities 
  end
  resources :account_types, :accounts, :addresses, :administrators, :customers, :transaction_types, :acct_transactions, :users
  resources :coin_accounts, :equity_types, :equities
  

  namespace :admin do
    
    resources :administrators do
     member do
      get :adminview
      get :manage_accounts
      get :manage_customers
      get :manage_acct_transactions
      get :manage_equities
      get :create_customer_account
     end
    end
    resources :accounts do
      resources :acct_transactions
    end
    resources :risks do
      resources :equities 
    end
    resources :users do
     resources :customers
    end
    resources :state do
     resources :zip_codes
    end
    resources :coin_accounts do
      resources :acct_transactions
    end  
    resources :payees do
      resources :acct_transactions
    end
    resources :customers do
      resources :addresses, :accounts, :coin_accounts, :equities
  
      resources :accounts do
        resources :acct_transactions do
          member do
           get :place_onhold
           get :process_transaction
           get :reverse_transaction
          end
        end
      end
        
    end
    
  end
end

app/controllers/acct_transactions_controller.rb
class AcctTransactionsController < ApplicationController
  layout "customer"
  before_action :authenticate_user!
  before_action :set_acct_transaction, only: [:show, :edit, :update, :destroy, :confirmtf]
  #before_action :gen_tac, only: [:confirmtf,:to_confirm]

  # GET /acct_transactions
  # GET /acct_transactions.json
  def index
    @acct_transactions = AcctTransaction.all
  end

  def confirmtf
    @payee = @acct_transaction.payee
    @account = Account.find(@acct_transaction.account_id)
    @tac = @acct_transaction.secure_tac
    AcctTransactionMailer.secure_tac(@tac,current_user.email,my_customer.name,@acct_transaction.id).deliver
  end
  def to_confirm
    @account = Account.find(params[:account_id])
    @recipient = Account.find('10000001887')
   if params[:search]
      @acct_transaction = AcctTransaction.find_by_secure_tac(params[:search])
      unless @acct_transaction.nil?
      @acct_transactions = AcctTransaction.transfer(@account,@recipient,@acct_transaction.amount,@acct_transaction)
      @acct_transaction.confirm!
       redirect_to customer_account_acct_transaction_path(my_customer,@acct_transaction.account_id,@acct_transaction.id)
      else
        redirect_to :back
      end
    else
      redirect_to root_path
     #redirect_to confirmtf_customer_account_acct_transaction_path(my_customer,@acct_transaction.account_id,@acct_transaction.id)
   end
  end
  # GET /acct_transactions/1
  # GET /acct_transactions/1.json
  def show
    @account = Account.find(@acct_transaction.account_id)
    @payee = @acct_transaction.payee
    #@recipient = Account.find(@acct_transaction.recipient_acct)
    if @acct_transaction.wire_transfers.present?
     @wire_transfer = @acct_transaction.wire_transfers.find_by_acct_transaction_id(params[:id])    
    end
  end

  # GET /acct_transactions/new
  def new
      @acct_transaction = AcctTransaction.new
      @acct_transaction.id = SecureRandom.random_number(99999999999999)
      @acct_transaction.account_id = params[:account_id]
      #@acct_transaction.date = Time.now
      #@acct_transaction.transaction_type_id = params[:transaction_type_id]
      @acct_transaction.amount = params[:amount]
      @wire_transfer = @acct_transaction.wire_transfers.new
    # for the view - show 'name' of transaction types
    #@trans_type = TransactionType.find(params[:transaction_type_id]).name
  end

  # GET /acct_transactions/1/edit
  def edit
  end

  # POST /acct_transactions
  # POST /acct_transactions.json
  def create
    #@acct_transaction.date = Time.now
    @acct_transaction = AcctTransaction.new(acct_transaction_params)
    @acct_transaction.id = SecureRandom.random_number(99999999999999)
    #@customer = Account.find(@acct_transaction.account_id)
    #@recipient = Account.find('10000001887')
    #@amount = params[:amount]
    @acct_transaction.recipient_id = 10000001887
    #@acct_transactions = AcctTransaction.transfer(@customer,@recipient,@acct_transaction.amount)
    #@acct_transaction.recipient_id = @recipient.id.to_i
    
    @acct_transaction.secure_tac = SecureRandom.random_number(99999999999999)
    #if @acct_transaction.valid?
    adjust_balance
    #end
    @acct_transaction.save!
    respond_to do |format|
      if @acct_transaction.valid?
        
        #modify_acct_balance
        logger.info "Transaction was just created"
        #@acct_transaction.confirm!
        if admin?
         format.html { redirect_to admin_payee_acct_transactions_path(@acct_transaction), notice: 'Acct transaction was successfully created.' }
        elsif @acct_transaction.pending?
          #@tac = SecureRandom.random_number(99999999999999)
          #AcctTransactionMailer.secure_tac(@tac,current_user.email,my_customer.name).deliver
          format.html { redirect_to confirmtf_customer_account_acct_transaction_path(my_customer,
          @acct_transaction.account_id,@acct_transaction.id), notice: 'Acct transaction was successfully created.' }
        end
        format.json { render :show, status: :created, location: @acct_transaction }
      else
         flash[:error] = @acct_transaction.errors
        format.html { redirect_to :back, :flash => { :alert => "INSUFFICIENT FUNDS!! Contact your relationship manager" } }
        format.json { render json: @acct_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acct_transactions/1
  # PATCH/PUT /acct_transactions/1.json
  def update
    respond_to do |format|
      if @acct_transaction.update(acct_transaction_params)
        format.html { redirect_to @acct_transaction, notice: 'Acct transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @acct_transaction }
      else
        format.html { render :edit }
        format.json { render json: @acct_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acct_transactions/1
  # DELETE /acct_transactions/1.json
  def destroy
    @acct_transaction.destroy
    respond_to do |format|
      format.html { redirect_to acct_transactions_url, notice: 'Acct transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acct_transaction
      @acct_transaction = AcctTransaction.find(params[:id])
    end
    def gen_tac
      @tac = SecureRandom.random_number(99999999999999)
      session[:tac] = @tac
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def acct_transaction_params
      params.require(:acct_transaction).permit(:account_id,:recipient_id,:payee_id, :recipient_acct,:date, :transaction_type_id, :description, :amount, :adjusted_bal, wire_transfers_attributes:[:id, :acct_transaction_id, :routing])
    end
    

  public
    def modify_acct_balance
      @account = Account.find(@acct_transaction.account_id)
     #@recipient = Account.find(@acct_transaction.recipient_acct)
   case @acct_transaction.transaction_type_id
    when 1,2,4,5,7
        @account.update_attributes!(balance: @account.balance - @acct_transaction.amount)
    when 3
       @account.update_attributes!(balance: @account.balance + @acct_transaction.amount)
    when 6,8
     @recipient = Account.find(@acct_transaction.recipient_acct)
     ActiveRecord::Base.transaction do
      @account.update(balance: @account.balance - @acct_transaction.amount)
      @recipient.update(balance: @recipient.balance + @acct_transaction.amount)
     end
       when 9
        @account.update_attributes!(balance: @account.balance - @acct_transaction.amount)
    end
  end
    def adjust_balance
      @account = Account.find(@acct_transaction.account_id)
      case @acct_transaction.transaction_type_id
          when 1,2,4,5,7
            @acct_transaction.adjusted_bal = Account.find(@acct_transaction.account_id).balance - @acct_transaction.amount
            when 3
              @acct_transaction.adjusted_bal = Account.find(@acct_transaction.account_id).balance + @acct_transaction.amount
          when 6,8
            @acct_transaction.adjusted_bal = Account.find(@acct_transaction.account).balance - @acct_transaction.amount
          when 9
           @acct_transaction.adjusted_bal = @account.balance
      end
    end
end

app/controllers/admin/acct_transactions_controller.rb
class Admin::AcctTransactionsController < Admin::ApplicationController
  layout "admin"
  before_action :set_acct_transaction, only: [:show, :edit, :update, :destroy,:reverse_transaction, :process_transaction, :place_onhold]

  # GET /acct_transactions
  # GET /acct_transactions.json
  def index
    @acct_transactions = AcctTransaction.all
  end

  def process_transaction
    @payee = @acct_transaction.payee
    @account = Account.find(@acct_transaction.account_id)
    AcctTransactionMailer.processe(@account.customer.user.email,@account.customer.name,@acct_transaction.id,@acct_transaction,@payee,@account).deliver
    @acct_transaction.process!
    redirect_to customer_account_acct_transaction_path(@account.customer_id,@acct_transaction.account_id,@acct_transaction.id)
  end
  def place_onhold
    @payee = @acct_transaction.payee
    @account = Account.find(@acct_transaction.account_id)
    AcctTransactionMailer.p_onhold(@account.customer.user.email,@account.customer.name,@acct_transaction.id,@acct_transaction,@payee,@account).deliver
    @acct_transaction.ongoing!
    redirect_to customer_account_acct_transaction_path(@account.customer_id,@acct_transaction.account_id,@acct_transaction.id)
  end
  def reverse_transaction
    @account = Account.find(@acct_transaction.account_id)
    @recipient = Account.find('10000001887')
    @amount = params[:amount]
    @acct_transactions = AcctTransaction.reverse(@recipient,@account,@acct_transaction.amount,@acct_transaction)
    @acct_transaction.reversing!
    redirect_to root_path
  end
  # GET /acct_transactions/1
  # GET /acct_transactions/1.json
  def show
    @account = Account.find(@acct_transaction.account_id)
    #@recipient = Account.find(@acct_transaction.recipient_acct)
    if @acct_transaction.wire_transfers.present?
     @wire_transfer = @acct_transaction.wire_transfers.find_by_acct_transaction_id(params[:id])    
    end
  end

  # GET /acct_transactions/new
  def new
      @acct_transaction = AcctTransaction.new
      @acct_transaction.id = SecureRandom.random_number(99999999999999)
      @acct_transaction.account_id = params[:account_id]
      #@acct_transaction.date = Time.now
      #@acct_transaction.transaction_type_id = params[:transaction_type_id]
      @acct_transaction.amount = params[:amount]
      @wire_transfer = @acct_transaction.wire_transfers.new
    # for the view - show 'name' of transaction types
    #@trans_type = TransactionType.find(params[:transaction_type_id]).name
  end

  # GET /acct_transactions/1/edit
  def edit
  end

  # POST /acct_transactions
  # POST /acct_transactions.json
  def create
    @acct_transaction = AcctTransaction.new(acct_transaction_params)
    @acct_transaction.id = SecureRandom.random_number(99999999999999)
    #@acct_transaction.date = Time.now
    #@wire_transfer = @acct_transaction.wire_transfers.build
    #@acct_transaction.wire_transfers.routing = params[:routing]
    if @acct_transaction.valid?
    adjust_balance
    end
 
    respond_to do |format|
      if @acct_transaction.save
        modify_acct_balance
        logger.info "Transaction was just created"
        format.html { redirect_to @acct_transaction, notice: 'Acct transaction was successfully created.' }
        format.json { render :show, status: :created, location: @acct_transaction }
      else
        # flash[:error] = @acct_transaction.errors
        format.html { redirect_to new_account_acct_transactions_path(@acct_transaction.account_id, :transaction_type_id => @acct_transaction.transaction_type_id), :flash => { :alert => "INSUFFICIENT FUNDS!! Contact your relationship manager" } }
        format.json { render json: @acct_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acct_transactions/1
  # PATCH/PUT /acct_transactions/1.json
  def update
    respond_to do |format|
      if @acct_transaction.update(acct_transaction_params)
        format.html { redirect_to @acct_transaction, notice: 'Acct transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @acct_transaction }
      else
        format.html { render :edit }
        format.json { render json: @acct_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acct_transactions/1
  # DELETE /acct_transactions/1.json
  def destroy
    @acct_transaction.destroy
    respond_to do |format|
      format.html { redirect_to acct_transactions_url, notice: 'Acct transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acct_transaction
      @acct_transaction = AcctTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acct_transaction_params
      params.require(:acct_transaction).permit(:account_id, :recipient_acct, :transaction_type_id, :description, :amount, :adjusted_bal, wire_transfers_attributes:[:id, :acct_transaction_id, :routing])
    end
    

  public
    def modify_acct_balance
      @account = Account.find(@acct_transaction.account_id)
     #@recipient = Account.find(@acct_transaction.recipient_acct)
   case @acct_transaction.transaction_type_id
    when 1,2,4,5,7
        @account.update_attributes!(balance: @account.balance - @acct_transaction.amount)
    when 3
       @account.update_attributes!(balance: @account.balance + @acct_transaction.amount)
    when 6,8
     @recipient = Account.find(@acct_transaction.recipient_acct)
     ActiveRecord::Base.transaction do
      @account.update(balance: @account.balance - @acct_transaction.amount)
      @recipient.update(balance: @recipient.balance + @acct_transaction.amount)
     end
       when 9
        ActiveRecord::Base.transaction do
      @account.update(balance: @account.balance - @acct_transaction.amount)
       #@wire_transfer = WireTransfer.new(routing: params[:routing])
      #@wire_transfer.save!
      end
    end
  end
    def adjust_balance
      case @acct_transaction.transaction_type_id
          when 1,2,4,5,7
            @acct_transaction.adjusted_bal = Account.find(@acct_transaction.account_id).balance - @acct_transaction.amount
            when 3
              @acct_transaction.adjusted_bal = Account.find(@acct_transaction.account_id).balance + @acct_transaction.amount
          when 6,8
            @acct_transaction.adjusted_bal = Account.find(@acct_transaction.account).balance - @acct_transaction.amount
          when 9
          @acct_transaction.adjusted_bal = Account.find(@acct_transaction.account).balance - @acct_transaction.amount
      end
    end
end

app/views/acct_transactions/_form.html.erb
<!--  Barnabas Bulpett
      WEB-289-YD1
      Spring 2015
      acct_transactions/_form.html.erb
-->
<!-- Dynamically generated partial for AcctTransaction model forms-->
<main>
<div class="panel" style="margin: 10px; padding: 20px;">  

  <%= bootstrap_nested_form_for(@acct_transaction) do |f| %>
  <% if @acct_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acct_transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @acct_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
        <!-- pre-filled (static) fields -->
        
        <%#= f.select :transaction_type_id, TransactionType.all.collect {|p| [ p.name, p.id ] }, class: "selectpicker btn-lg btn-default",prompt: 'Select Transaction type' %>
        
          <br />
          Date: <strong><%= Time.now.to_date %></strong></p>
        <%= f.hidden_field :date, :value => Time.now %>
        <!-- fields for AcctTransaction object -->
        
        <%= f.text_field :description, :style =>"max-width: 550px;" %>
        
        <div id="tip">
          <%= f.number_field :amount, :style =>"width: 160px;" %>
        <p style="line-height: 1.2em;">
           <em>Fill the amount in numerals without a space or coma. For example (1000). <br />
           All transactions are done in dollars</em></p>
        </div>
        <%= f.select( :account_id, my_customer.accounts.collect {|p| [ p.id ] } ) %>
        <%#= f.hidden_field :account_id, :value => params[:account_id] %>
        <%= f.hidden_field :payee_id, :value => params[:payee_id] %>
        <%= f.hidden_field :transaction_type_id, :value => params[:transaction_type_id] %>
        <%#= f.hidden_field :transaction_type_id, :value => @acct_transaction.transaction_type_id %>
          <%= f.fields_for :payee do |fa| %>
           <%= fa.text_field :account_number, required: true %>
           <%= fa.text_field :ref_name %>
           <%= fa.text_field :bank_name, required: true %>
           <%= fa.text_field :routing_number %>
           <%= fa.text_field :swift_code %>
           <%= fa.text_field :address, required: true %>
           <%= fa.text_field :city, required: true %>
           <%= fa.text_field :state, required: true %>
           <%= fa.text_field :country, required: true %>
           <%= fa.text_field :post_code, required: true %>
           <%= fa.text_field :phone %>
           <%= fa.select :title, options_for_select(['Debit', 'Credit']) %>
           <%#= f.hidden_field :acct_transaction_id, :value => params[:acct_transaction_id] %>
          <% end %>
      <div class="actions">
        <%= f.submit "Complete Transaction", :class => "btn btn-info"%>
      </div>
    <% end %>
  </div>
</main>

app/views/acct_transactions/confirmtf.html.erb
<!-- 	Barnabas Bulpett
		WEB-289-YD1
		Spring 2015
		acct_transactions/show.html.erb
-->
<!-- Dynamic view (partial) showing details of transaction -->
<% content_for :customer_content do %>
<main>
	<div id="panel">
		<!-- Display attributes for chosen AcctTransaction object -->
		<h3>Summary for Transaction no. <%= @acct_transaction.id %></h3>
		<ul>
			<li>Account: <%= @acct_transaction.account_id%></li>
			<li>Type: <%= TransactionType.find(@acct_transaction.transaction_type_id).name %></li>
			<li>Date: <%= time_tag(@acct_transaction.date) %></li>
			<li>Amount: <%= number_to_currency(@acct_transaction.amount)%></li>
			<li>Description: <%= @acct_transaction.description %></li>
			<li>Beneficiary Name: <%= @payee.ref_name %></li>
			<li>Beneficiary Bank Account: <%= @payee.acct_number%></li>
			<li>Beneficiary Bank: <%= @payee.bank_name %></li>
			<li>Beneficiary City: <%= @payee.city %></li>
			<li>Beneficiary Country: <%= @payee.country %></li>
    <% unless @wire_transfer.nil? %>
    <li>Recipient Name: <%= @wire_transfer.recipient_name %></li>
    <li>Amount Credited: <%= @wire_transfer.credited %></li>
    <li>Recipient Account: <%= @wire_transfer.bank_account %></li>
    <li>Recipient Address: <%= @wire_transfer.address %></li>
    <li>Recipient City: <%= @wire_transfer.city %></li>
    <li>Recipient State: <%= @wire_transfer.state %></li>
    <li>Recipient Country: <%= @wire_transfer.country %></li>
    <li>Recipient Bank: <%= @wire_transfer.bank_name %></li>
    <li>Bank Routing: <%= @wire_transfer.routing %></li>
    <li>Bank Country: <%= @wire_transfer.bank_country %></li>
    <li>Transaction ID: <%= @wire_transfer.acct_transaction_id%></li>
    <li>Description: <%= @wire_transfer.description %></li>

  <% end %>
		</ul>
	<div>
	<!-- Action buttons -->
	<div id="links-block">
		<% if current_user.role == 'admin' %>
		<%= link_to 'Back', :back, :class => "btn btn-primary formButton"  %>
		<%= link_to 'Return to Dashboard', manage_acct_transactions_administrator_path, :class => "btn btn-info formButton"  %>
		<% elsif @acct_transaction.pending? %>
		<p>Check your email <%= current_user.email %> for your transaction token</p>
		<%#= link_to 'Confirm transaction', "", :class => "btn btn-primary formButton"  %>
		<%= form_tag to_confirm_customer_account_acct_transaction_path, :method => 'get', :id => "search-form", :class => "tacBox" do %>
            <%= text_field_tag :search, params[:search], required: true  %>
            
            <%= submit_tag "Confirm Transaction", :name => nil, :class => "btn btn-primary formButton" %>
          <% end %>
		<% else %>
		<%= link_to 'Your transaction is under processing', '', :class => "btn btn-primary formButton" %>
		
		<%= link_to 'Back to Account', account_path(@acct_transaction.account_id), :class => "btn btn-primary formButton"  %>
		<% end %>
	</div>
</main>
<% end %>

app/views/acct_transactions/edit.html.erb
<!--  Barnabas Bulpett
      WEB-289-YD1
      Spring 2015
      acct_transactions/edit.html.erb
-->
<!-- Dynamically generated partial for AcctTransaction model editing-->
<h1>Editing acct_transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @acct_transaction %> |
<%= link_to 'Back', acct_transactions_path %>

app/views/acct_transactions/new.html.erb
<!--  Barnabas Bulpett
      WEB-289-YD1
      Spring 2015
      acct_transactions/new.html.erb
-->
<!-- Dynamically generated partial for new AcctTransaction model -->
<% content_for :customer_content do %>
<h2>New Account Transaction for Account No. <%= params[:account_id] %></h2>

<% unless params[:transaction_type_id] = 9 %>
<%= render 'wireform' %>
<% else %>
<%= render 'form' %>
<% end %>

<%#= render 'form' %>

<div id="links-block">
<%= link_to 'Back', :back, :class => "btn btn-primary formButton" %>
</div>
<% end %>

app/views/acct_transactions/show.html.erb
<!-- 	Barnabas Bulpett
		WEB-289-YD1
		Spring 2015
		acct_transactions/show.html.erb
-->
<!-- Dynamic view (partial) showing details of transaction -->
<% content_for :customer_content do %>
<main>
	<div id="panel">
		<!-- Display attributes for chosen AcctTransaction object -->
		<h3>Summary for Transaction no. <%= @acct_transaction.id %></h3>
		<ul>
			<li>Account: <%= @acct_transaction.account_id%></li>
			<li>Transaction Status: <%= @acct_transaction.status %></li>
			<li>Type: <%= @acct_transaction.transaction_type.name %></li>
			<li>Date: <%= time_tag(@acct_transaction.date) %></li>
			<li>Amount: <%= number_to_currency(@acct_transaction.amount)%></li>
			<li>Description: <%= @acct_transaction.description %></li>
			<li>Beneficiary Name: <%= @payee.ref_name %></li>
			<li>Beneficiary Bank Account: <%= @payee.acct_number%></li>
			<li>Beneficiary Bank: <%= @payee.bank_name %></li>
			<li>Beneficiary City: <%= @payee.city %></li>
			<li>Beneficiary Country: <%= @payee.country %></li>
    <% unless @wire_transfer.nil? %>
    <li>Recipient Name: <%= @wire_transfer.recipient_name %></li>
    <li>Amount Credited: <%= @wire_transfer.credited %></li>
    <li>Recipient Account: <%= @wire_transfer.bank_account %></li>
    <li>Recipient Address: <%= @wire_transfer.address %></li>
    <li>Recipient City: <%= @wire_transfer.city %></li>
    <li>Recipient State: <%= @wire_transfer.state %></li>
    <li>Recipient Country: <%= @wire_transfer.country %></li>
    <li>Recipient Bank: <%= @wire_transfer.bank_name %></li>
    <li>Bank Routing: <%= @wire_transfer.routing %></li>
    <li>Bank Country: <%= @wire_transfer.bank_country %></li>
    <li>Transaction ID: <%= @wire_transfer.acct_transaction_id%></li>
    <li>Description: <%= @wire_transfer.description %></li>

  <% end %>
		</ul>
	<div>
	<!-- Action buttons -->
	<div id="links-block">
		<% if current_user.role == 'admin' %>
		<%= link_to 'Back', :back, :class => "btn btn-primary formButton"  %>
		<%= link_to 'Return to Dashboard', manage_acct_transactions_admin_administrator_path, :class => "btn btn-info formButton"  %>
		  <% if @acct_transaction.confirmed? %>
		    <%= link_to 'Place on hold', place_onhold_admin_customer_account_acct_transaction_path(my_customer,@acct_transaction.account_id,@acct_transaction.id), :class => "btn btn-primary formButton" %>
		    <% else %>
		    <%= link_to 'Process Transaction', process_transaction_admin_customer_account_acct_transaction_path(my_customer,@acct_transaction.account_id,@acct_transaction.id), :class => "btn btn-info formButton"  %> 
		  <% end%>
		<% else %>
		<%= link_to 'Back to Account', account_path(@acct_transaction.account_id), :class => "btn btn-primary formButton"  %>
		   <% if @acct_transaction.confirmed? %>
            <%= link_to 'Your transaction is under processing', '', :class => "btn btn-primary formButton"  %>
            <% elsif @acct_transaction.pending? %>
            <%= link_to 'Your transaction is not confirmed', confirmtf_customer_account_acct_transaction_path(my_customer,@acct_transaction.account_id,@acct_transaction.id), :class => "btn btn-primary formButton" %>
            <% elsif @acct_transaction.onhold? %>
             <%= link_to 'Your transaction is on hold', '', :class => "btn btn-primary formButton" %>
           <% end %>
		<% end %>
	</div>
</main>
<% end %>